server:
  port: 8080

spring:
  application:
    name: product

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT:5432}/store
    username: ${DATABASE_USER:store}
    password: ${DATABASE_PASSWORD:store}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: product

  flyway:
    schemas: product
    baseline-on-migrate: true

  cache:
    type: redis

  redis:
    host: redis
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
